### ISSUE TITLE
Configuration .yml file

### ISSUE THREAD

**Issue by skofieldO5** [curso-r/auth0#4]
Thanks for your package. I think I'm doing something wrong with the configuration of the _auth0.yml file. Hereis what I have:

```
name: myApp
shiny_config: http://localhost:8100
auth0_config:
  api_url: 'shiny-apps.eu.auth0.com'
  credentials:
    key: !expr Sys.getenv("CLIENTIDFROMAUTH0")
    secret: !expr Sys.getenv("CLIENTSECRETFROMAUTH0")
```

When I then run `shiny::runApp("app.R", port = 8100)` the URL my browser goes to is 

`http://127.0.0.1:8100/:///:///shiny-apps.eu.auth0.com/authorize?client_id=&scope=openid%20profile&redirect_uri=http%3A%2F%2Flocalhost%3A8100&response_type=code&state=xeovxv792u`

The URL is "Not Found". Can you help me out what I'm doing wrong here? Thanks

**Comment by DavidPatShuiFong** [comment]
For what it's worth, I got the same error when I didn't specify the api_url correctly.  Is the contents of api_url really the same as the DOMAIN box of your auth0 application?

**Comment by jtrecenti** [comment]
Did you set the enviroment variables?

You have two options:

## Editing `.Renviron` file

1. Run `usethis::edit_r_environ()`
2. Add the folowing lines:

```
AUTH0_USER=
AUTH0_KEY=
AUTH0_SECRET=
```

3. Restart your session
4. Your `_auth0.yml` should look like

```
name: myApp
shiny_config:
  local_url: http://localhost:8100
  remote_url: ''
auth0_config:
  api_url: !expr paste0('https://', Sys.getenv("AUTH0_USER"), '.auth0.com')
  credentials:
    key: !expr Sys.getenv("AUTH0_KEY")
    secret: !expr Sys.getenv("AUTH0_SECRET")
```

5. Run `shiny::runApp("app.R", port = 8100)`

## Adding the key and secret directly

1. Your `_auth0.yml` will look like

```
name: myApp
shiny_config:
  local_url: http://localhost:8100
  remote_url: ''
auth0_config:
  api_url: https://shiny-apps.eu.auth0.com
  credentials:
    key: 'JOHNDOEKEY'
    secret: 'JOHNDOESECRET'
```

Please tell us if it works
