### ISSUE TITLE
Something went wrong: There could be a misconfiguration in the system or a service outage

### ISSUE THREAD

**Issue by MislavSag** [curso-r/auth0#51]
After went through all the steps https://curso-r.github.io/auth0/index.html and ran my app,  got following error in browser:

> Looks like something went wrong!
> 
> There could be a misconfiguration in the system or a service outage. We track these errors automatically, but if the problem persists feel free to contact us with this tracking id: 
> 
> dd894f6a5569beadc98c.
> 
> Please try again.

**Comment by jtrecenti** [comment]
Hi! Could you share print screens of

1) the page where the error appears
2) your auth0 app configuration page

Just make sure to hide any key/secrets of they appear. Thanks!

**Comment by MislavSag** [comment]
The page where the error appears

![image](https://user-images.githubusercontent.com/33196375/66304844-6c6e0e80-e8fe-11e9-9020-23f715acb375.png)

Auth0 app configuration page:

```
name: TelefoniPlu
remote_url: ''
auth0_config:
  api_url: !expr paste0('https://', Sys.getenv('AUTH0_USER'), '.auth0.com')
  credentials:
    key: !expr Sys.getenv("AUTH0_KEY")
    secret: !expr Sys.getenv("AUTH0_SECRET")
```

R enviroment file:
AUTH0_USER=dev-n4dc-e-s
AUTH0_KEY=Awj7xxxxxxxx
AUTH0_SECRET=tO_Ta1RzxxPxxxxxxxxxxx

I also tried to manually add key, secret and user to _auth0 file.
