### ISSUE TITLE
Problems with Search Parameters 

### ISSUE THREAD

**Issue by LepiorzDaniel** [curso-r/auth0#67]
I use Auth0 for the authentication of my Shiny APP. Now everything works fine, but I need a parameter that should be passed when calling the URL. When testing with localhost and AUth0 everything worked fine. But when I deploy the APP with RStudio Connect, the parameters are always deleted after authentication. How can I fix this problem? The parameter changes all the time, so I need some kind of wildcard.

This is what my _auth0.yml looks like in the Shiny APP:

```
name: SHINY APP
remote_url: https://server:port/folder/subfolder
auth0_config:
  api_url: https://api-url.auth0.com
  credentials:
    key: "xxx"
    secret: "xxx"
```
When I call the URL: https://server:port/folder/subfolder everything works fine. But now I need a URL Paramter like this: https://server:port/folder/subfolder/?number=8899988

When I call this url Auth0 works fine but direct my to: https://server:port/folder/subfolder

I tried it with https://server:port/folder/subfolder/?number=* but this does not work as remote_url. I have already entered all urls in the Auth0 settings, but without success. If I leave the remote_url empty I always get a random localhost address, but I can’t unlock it at Auth0 because the port is always changing here. With Localhost the parameter transfer and Auth0 works correctly.
