### ISSUE TITLE
`auth_info` null on shinyapps

### ISSUE THREAD

**Issue by chintanp** [curso-r/auth0#72]
Authentication works fine, but when I try to use the value of `session$userData$auth_info`, it is NULL. 
```R
 observeEvent(input$submitButton, {
    # ulid_submit <- ulid::ULIDgenerate()
    dt_submit <- Sys.time()
    auth0_sub <- session$userData$auth0_info$sub
    auth0_userid <-
      strsplit(auth0_sub, "|", fixed = TRUE)[[1]][2]
    user_name <- session$userData$auth0_info$name
    user_email <- session$userData$auth0_info$email
...
```
This works locally. Is it possible that `shinyapps` has a different version of `auth0` package or underlying API that makes the `session$userData` NULL.

**Comment by jtrecenti** [comment]
Hi @chintanp, thanks for the issue. 

My apps run with userinfo locally and in shinyapps.io, using the same configuration. 

Working example (try to login with google): https://jubs.shinyapps.io/userinfo

Are you using `app.R` or `ui.R/server.R` paradigm?

**Comment by chintanp** [comment]
@jtrecenti I am using `app.R`. Is the code for your example app public somewhere?

**Comment by jtrecenti** [comment]
It's the example from the documentation. I've just added a `logoutButton()`.

https://curso-r.github.io/auth0/articles/examples/userinfo.html

**Comment by chintanp** [comment]
@jtrecenti Thanks. So it seems that the way to get to `auth_info` is to call it in a reactive context, which I think I am doing. 

My `_auth0.yml` file, in case I messed something up here: 

```
name: myApp
remote_url: https://cp84.shinyapps.io/evi_des/
shiny_config: http://localhost:8100
auth0_config:
  scope: "openid email profile"
  api_url: !expr paste0('https://', Sys.getenv('AUTH0_USER'), '.auth0.com')
  credentials:
    key: !expr Sys.getenv("AUTH0_KEY")
    secret: !expr Sys.getenv("AUTH0_SECRET")

```
