### ISSUE TITLE
Callback URL Mismatch

### ISSUE THREAD

**Issue by dvera** [curso-r/auth0#98]
Getting callback URL mismiatch.

Running shiny app behind nginx which also handles ssl

auth0 callback URL contains
```
https://<SUBDOMAIN>.<DOMAIN>.<TLD>
```

`_auth0.yml`
```
name: app
remote_url: 'https://<SUBDOMAIN>.<DOMAIN>.<TLD>'
auth0_config:
  api_url: 'https://<USERNAME>.us.auth0.com'
  credentials:
    key: '<KEY>'
    secret: '<SECRET>'
```

`nginx.conf`
```
server {
        listen 443 ssl;
        server_name <SUBDOMAIN>.<DOMAIN>.<TLD> ;
        ssl_certificate         /etc/letsencrypt/live/<SUBDOMAIN>.<DOMAIN>.<TLD>/fullchain.pem;
        ssl_certificate_key     /etc/letsencrypt/live/<SUBDOMAIN>.<DOMAIN>.<TLD>/privkey.pem;
        location / {
                proxy_pass         "http://127.0.0.1:8888";
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_read_timeout 600s;
                proxy_redirect    off;
                proxy_set_header  Host              $http_host;
                proxy_set_header  X-Real-IP         $remote_addr;
                proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header  X-Forwarded-Proto https;
        }
}
```

`R`
```
library(shiny)
options(shiny.port=8888)
runApp("app", port = 8888 , launch.browser = F)
```

Result:
<img width="1106" alt="image" src="https://github.com/curso-r/auth0/assets/5902410/76ed98c7-e990-4df2-8ce1-7d1381285efa">
